### ISSUE TITLE
How to create token key from code behind

### ISSUE THREAD

**Issue by VickyMahir** [2Checkout/2checkout-dotnet#1]
Hi

I want to know how to generate token key from user account details using code behind web request.

Thanks

Vijay Maheriya

**Comment by craigchristenson** [comment]
With the Payment API, a token can only be created client side [using the 2co.js JavaScript library](https://www.2checkout.com/documentation/payment-api/create-token). These are single use tokens that can be used only once to place a transaction. Your API keys can be created and accessed under the API tab in your 2Checkout seller account admin. Please contact techsupport@2co.com with any questions on your account.
